# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 373)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0852273, y1:0.102, x2:1, y2:1, stop:0 rgba(23, 39, 42, 255), stop:1 rgba(227, 211, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.generate_button = QtWidgets.QPushButton(self.centralwidget)
        self.generate_button.setGeometry(QtCore.QRect(270, 170, 100, 50))
        self.generate_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.generate_button.setObjectName("generate_button")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 80, 451, 71))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 0, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.telekom_button = QtWidgets.QRadioButton(self.layoutWidget)
        self.telekom_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.telekom_button.setObjectName("telekom_button")
        self.verticalLayout_2.addWidget(self.telekom_button)
        self.vodafone_button = QtWidgets.QRadioButton(self.layoutWidget)
        self.vodafone_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.vodafone_button.setObjectName("vodafone_button")
        self.verticalLayout_2.addWidget(self.vodafone_button)
        self.telefonica_button = QtWidgets.QRadioButton(self.layoutWidget)
        self.telefonica_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.telefonica_button.setObjectName("telefonica_button")
        self.verticalLayout_2.addWidget(self.telefonica_button)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lte_button = QtWidgets.QRadioButton(self.layoutWidget)
        self.lte_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lte_button.sizePolicy().hasHeightForWidth())
        self.lte_button.setSizePolicy(sizePolicy)
        self.lte_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.lte_button.setChecked(True)
        self.lte_button.setObjectName("lte_button")
        self.verticalLayout.addWidget(self.lte_button)
        self.umts_button = QtWidgets.QRadioButton(self.layoutWidget)
        self.umts_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.umts_button.setObjectName("umts_button")
        self.verticalLayout.addWidget(self.umts_button)
        self.gsm_button = QtWidgets.QRadioButton(self.layoutWidget)
        self.gsm_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.gsm_button.setObjectName("gsm_button")
        self.verticalLayout.addWidget(self.gsm_button)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 3, 1, 1)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 0, 5, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.dateLabel_2 = QtWidgets.QLabel(self.layoutWidget)
        self.dateLabel_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.dateLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel_2.setObjectName("dateLabel_2")
        self.gridLayout_2.addWidget(self.dateLabel_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("timeLabel")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.timeEdit = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.timeEdit.setObjectName("startTime")
        self.gridLayout_2.addWidget(self.timeEdit, 1, 1, 1, 1)
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.layoutWidget)
        self.timeEdit_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.timeEdit_2.setObjectName("endTime")
        self.gridLayout_2.addWidget(self.timeEdit_2, 2, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 9, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 0, 7, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.dateLabel = QtWidgets.QLabel(self.layoutWidget)
        self.dateLabel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.gridLayout.addWidget(self.dateLabel, 0, 1, 1, 1)
        self.startDate = QtWidgets.QDateEdit(self.layoutWidget)
        self.startDate.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.startDate.setObjectName("startDate")
        self.gridLayout.addWidget(self.startDate, 1, 1, 1, 1)
        self.endDate = QtWidgets.QDateEdit(self.layoutWidget)
        self.endDate.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.endDate.setObjectName("endDate")
        self.gridLayout.addWidget(self.endDate, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 6, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 0, 8, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generate_button.setText(_translate("MainWindow", "Update"))
        self.telekom_button.setText(_translate("MainWindow", "Telekom"))
        self.vodafone_button.setText(_translate("MainWindow", "Vodafone"))
        self.telefonica_button.setText(_translate("MainWindow", "Telefonica"))
        self.lte_button.setText(_translate("MainWindow", "LTE"))
        self.umts_button.setText(_translate("MainWindow", "UMTS"))
        self.gsm_button.setText(_translate("MainWindow", "GSM"))
        self.label_3.setText(_translate("MainWindow", "End"))
        self.dateLabel_2.setText(_translate("MainWindow", "Time"))
        self.label_4.setText(_translate("MainWindow", "Start"))
        self.label_2.setText(_translate("MainWindow", "End"))
        self.dateLabel.setText(_translate("MainWindow", "Date"))
        self.label.setText(_translate("MainWindow", "Start"))
