# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 310)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.0852273, y1:0.102, x2:1, y2:1, stop:0 rgba(23, 39, 42, 255), stop:1 rgba(227, 211, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.generate_button = QtWidgets.QPushButton(self.centralwidget)
        self.generate_button.setGeometry(QtCore.QRect(300, 150, 100, 50))
        self.generate_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.generate_button.setObjectName("generate_button")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(240, 60, 111, 69))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.dateLabel = QtWidgets.QLabel(self.widget)
        self.dateLabel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.dateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.gridLayout.addWidget(self.dateLabel, 0, 1, 1, 1)
        self.startDate = QtWidgets.QDateEdit(self.widget)
        self.startDate.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.startDate.setObjectName("startDate")
        self.gridLayout.addWidget(self.startDate, 1, 1, 1, 1)
        self.endDate = QtWidgets.QDateEdit(self.widget)
        self.endDate.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.endDate.setObjectName("endDate")
        self.gridLayout.addWidget(self.endDate, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(370, 60, 128, 69))
        self.widget1.setObjectName("widget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.dateLabel_2 = QtWidgets.QLabel(self.widget1)
        self.dateLabel_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.dateLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateLabel_2.setObjectName("dateLabel_2")
        self.gridLayout_2.addWidget(self.dateLabel_2, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.startTime = QtWidgets.QTimeEdit(self.widget1)
        self.startTime.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.startTime.setObjectName("startTime")
        self.gridLayout_2.addWidget(self.startTime, 1, 1, 1, 1)
        self.endTime = QtWidgets.QTimeEdit(self.widget1)
        self.endTime.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.endTime.setObjectName("endTime")
        self.gridLayout_2.addWidget(self.endTime, 2, 1, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(130, 60, 81, 91))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lte_button = QtWidgets.QRadioButton(self.widget2)
        self.lte_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lte_button.sizePolicy().hasHeightForWidth())
        self.lte_button.setSizePolicy(sizePolicy)
        self.lte_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.lte_button.setChecked(True)
        self.lte_button.setObjectName("lte_button")
        self.verticalLayout.addWidget(self.lte_button)
        self.umts_button = QtWidgets.QRadioButton(self.widget2)
        self.umts_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.umts_button.setObjectName("umts_button")
        self.verticalLayout.addWidget(self.umts_button)
        self.gsm_button = QtWidgets.QRadioButton(self.widget2)
        self.gsm_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.gsm_button.setObjectName("gsm_button")
        self.verticalLayout.addWidget(self.gsm_button)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(30, 60, 74, 91))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.telekom_button = QtWidgets.QRadioButton(self.widget3)
        self.telekom_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.telekom_button.setObjectName("telekom_button")
        self.verticalLayout_2.addWidget(self.telekom_button)
        self.vodafone_button = QtWidgets.QRadioButton(self.widget3)
        self.vodafone_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.vodafone_button.setObjectName("vodafone_button")
        self.verticalLayout_2.addWidget(self.vodafone_button)
        self.telefonica_button = QtWidgets.QRadioButton(self.widget3)
        self.telefonica_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.telefonica_button.setObjectName("telefonica_button")
        self.verticalLayout_2.addWidget(self.telefonica_button)
        self.useTime = QtWidgets.QRadioButton(self.centralwidget)
        self.useTime.setGeometry(QtCore.QRect(400, 30, 82, 17))
        self.useTime.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.useTime.setObjectName("useTime")
        self.useDate = QtWidgets.QRadioButton(self.centralwidget)
        self.useDate.setGeometry(QtCore.QRect(250, 30, 91, 17))
        self.useDate.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.074, y1:0.107909, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(54, 81, 82, 255));")
        self.useDate.setObjectName("useDate")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(70, 170, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 542, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generate_button.setText(_translate("MainWindow", "Update"))
        self.label_2.setText(_translate("MainWindow", "End"))
        self.dateLabel.setText(_translate("MainWindow", "Date"))
        self.label.setText(_translate("MainWindow", "Start"))
        self.label_3.setText(_translate("MainWindow", "End"))
        self.dateLabel_2.setText(_translate("MainWindow", "Time"))
        self.label_4.setText(_translate("MainWindow", "Start"))
        self.lte_button.setText(_translate("MainWindow", "LTE"))
        self.umts_button.setText(_translate("MainWindow", "UMTS"))
        self.gsm_button.setText(_translate("MainWindow", "GSM"))
        self.telekom_button.setText(_translate("MainWindow", "Telekom"))
        self.vodafone_button.setText(_translate("MainWindow", "Vodafone"))
        self.telefonica_button.setText(_translate("MainWindow", "Telefonica"))
        self.useTime.setText(_translate("MainWindow", "setze Zeit"))
        self.useDate.setText(_translate("MainWindow", "setze Datum"))
